// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ticket_Web.Data;

#nullable disable

namespace Ticket_Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231102093656_AddTicketModal")]
    partial class AddTicketModal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Ticket_Web.Modal.Department", b =>
                {
                    b.Property<int>("iDepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("iDepartmentId"), 1L, 1);

                    b.Property<string>("vDepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("iDepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Ticket_Web.Modal.Role", b =>
                {
                    b.Property<int>("iRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("iRoleId"), 1L, 1);

                    b.Property<string>("vRoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("iRoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Ticket_Web.Modal.Ticket", b =>
                {
                    b.Property<int>("iTicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("iTicketId"), 1L, 1);

                    b.Property<int>("iCount")
                        .HasColumnType("int");

                    b.Property<string>("vImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vTicketName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("iTicketId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Ticket_Web.Modal.User", b =>
                {
                    b.Property<int>("iUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("iUserId"), 1L, 1);

                    b.Property<DateTime>("dExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dRefreshDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dRegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("iDepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("iRoleId")
                        .HasColumnType("int");

                    b.Property<string>("vAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vUserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("iUserId");

                    b.HasIndex("iDepartmentId");

                    b.HasIndex("iRoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ticket_Web.Modal.User", b =>
                {
                    b.HasOne("Ticket_Web.Modal.Department", "Department")
                        .WithMany()
                        .HasForeignKey("iDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticket_Web.Modal.Role", "Role")
                        .WithMany()
                        .HasForeignKey("iRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
